INVALID_SCHEMA = "INVALID_SCHEMA"
PUBLIC_SCHEMA = "public"
DB_NOT_UPTODATE = "DB_NOT_UPTODATE"
HEAD = "HEAD"
AUTHORIZATION = "Authorization"
INVALID_NOTIFICATION_TYPE = "INVALID_NOTIFICATION_TYPE"
USER_NOT_FOUND = "USER_NOT_FOUND"


#USER MANAGEMENT SERVICE RELATED CONSTANTS:
THE_USER_DETAILS_DOES_NOT_EXIST_FOR_THIS_ID = "THE_USER_DETAILS_DOES_NOT_EXIST_FOR_THIS_ID:"

#PROJECT MANAGEMENT SERVICE RELATED CONSTANTS:
PROJECT_HAS_BEEN_CREATED_SUCCESSFULLY_WITH_ID = "PROJECT_HAS_BEEN_CREATED_SUCCESSFULLY_WITH_ID:"
PROJECT_HAS_BEEN_UPDATED_SUCCESSFULLY_UPDATED_WITH_ID = "PROJECT_HAS_BEEN_UPDATED_SUCCESSFULLY_WITH_ID:"
PROJECT_NOT_FOUND = "THIS_PROJECT_NAME_NOT_FOUND" 
PROJECT_NAME_ALREADY_EXIST = "PROJECT_NAME_ALREADY_EXIST" 
CANNOT_DELETE_PROJECT_NAME_BECAUSE_IT_HAS_RELATED_FILE_NUMBERS = "CANNOT_DELETE_PROJECT_NAME_BECAUSE_IT_HAS_RELATED_FILE_NUMBERS"
PROJECT_HAS_BEEN_DELETED_SUCCESSFULLY_WITH_ID = "PROJECT_HAS_BEEN_DELETED_SUCCESSFULLY_WITH_ID:"  

#COSTCENTER MANAGEMENT SERVICE RELATED CONSTANTS :
COSTCENTER_HAS_BEEN_CREATED_SUCCESSFULLY_WITH_ID = "COSTCENTER_HAS_BEEN_CREATED_SUCCESSFULLY_WITH_ID:"
COSTCENTER_HAS_BEEN_UPDATED_SUCCESSFULLY_UPDATED_WITH_ID = "COSTCENTER_HAS_BEEN_UPDATED_SUCCESSFULLY_UPDATED_WITH_ID:"
COSTCENTER_NOT_FOUND = "THIS_COSTCENTER_NOT_FOUND" 
COSTCENTER_ALREADY_EXIST = "COSTCENTER_ALREADY_EXIST" 
CANNOT_DELETE_COSTCENTER_BECAUSE_IT_HAS_RELATED_FILE_NUMBERS = "CANNOT_DELETE_COSTCENTER_BECAUSE_IT_HAS_RELATED_FILE_NUMBERS"
COSTCENTER_HAS_BEEN_DELETED_SUCCESSFULLY_WITH_ID = "COSTCENTER_HAS_BEEN_DELETED_SUCCESSFULLY_WITH_ID:"  


#DOCUMENT TYPE MANAGEMENT SERVICE RELATED CONSTANTS :
DOCUMENT_TYPE_HAS_BEEN_CREATED_SUCCESSFULLY_WITH_ID = "DOCUMENT_TYPE_HAS_BEEN_CREATED_SUCCESSFULLY_WITH_ID:"
DOCUMENT_TYPE_HAS_BEEN_UPDATED_SUCCESSFULLY_WITH_ID = "DOCUMENT_TYPE_HAS_BEEN_UPDATED_SUCCESSFULLY_WITH_ID:"
DOCUMENT_TYPE_NOT_FOUND = "THIS_DOCUMENT_TYPE_NOT_FOUND" 
CANNOT_DELETE_DOCUMENT_TYPE_BECAUSE_IT_HAS_RELATED_FILE_NUMBERS = "CANNOT_DELETE_DOCUMENT_TYPE_BECAUSE_IT_HAS_RELATED_FILE_NUMBERS"
DOCUMENT_TYPE_HAS_BEEN_DELETED_SUCCESSFULLY_WITH_ID = "DOCUMENT_TYPE_HAS_BEEN_DELETED_SUCCESSFULLY_WITH_ID:" 

COST_CENTER_NAME_ALREADY_EXIST = "COST_CENTER_NAME_ALREADY_EXIST" 
DOCUMENT_TYPE_ALREADY_EXIST = "DOCUMENT_TYPE_ALREADY_EXIST" 


#FILE NUMBER MANAGEMENT SERVICE RELATED CONSTANTS:
INVALID_FILE_NUMBER_FORMAT = "INVALID_FILE_NUMBER_FORMAT"
FILE_NUMBER_DOES_NOT_EXISTS = "FILE_NUMBER_DOES_NOT_EXISTS"
FILE_NUMBER_DATA_NOT_FOUND = "FILE_NUMBER_DATA_NOT_FOUND" 

# USER MANAGEMENT SERVICE RELATED CONSTANTS :

USER_CREATED_SUCCESSFULLY = "USER_HAS_BEEN_SUCCESSFULLY_CREATED_WITH_EMAIL_ID"
EMAIL_ID_NOT_FOUND = "THIS_EMAIL_ID_IS_NOT_FOUND"
USER_EMAIL_ID_ALREADY_EXIST = "USER_EMAIL_ID_ALREADY_EXIST" 
ROLE_UPDATED_SUCCESSFULLY = "ROLE_UPDATED_SUCCESSFULLY"